<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="8" passed="3" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-25T07:07:03 UTC" name="Suite1" finished-at="2021-11-25T07:07:05 UTC" duration-ms="2114">
    <groups>
    </groups>
    <test started-at="2021-11-25T07:07:03 UTC" name="Test1" finished-at="2021-11-25T07:07:05 UTC" duration-ms="2114">
      <class name="eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:03 UTC" name="beforeSuite" finished-at="2021-11-25T07:07:03 UTC" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method signature="testT03_SimpleFailedTest()[pri:3, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:03 UTC" name="testT03_SimpleFailedTest" finished-at="2021-11-25T07:07:04 UTC" duration-ms="1027" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing for reasons]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing for reasons
at org.testng.Assert.fail(Assert.java:99)
at eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest.testT03_SimpleFailedTest(SimpleTest.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at eu.tsystems.mms.tic.testframework.report.hooks.TestMethodHook.runHook(TestMethodHook.java:60)
at eu.tsystems.mms.tic.testframework.report.TesterraListener.run(TesterraListener.java:433)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT03_SimpleFailedTest -->
        <test-method signature="testT02_SimplePassedTest()[pri:2, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:03 UTC" name="testT02_SimplePassedTest" finished-at="2021-11-25T07:07:04 UTC" duration-ms="1026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT02_SimplePassedTest -->
        <test-method signature="testT01_SimplePassedTest()[pri:1, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:03 UTC" name="testT01_SimplePassedTest" finished-at="2021-11-25T07:07:04 UTC" duration-ms="1007" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT01_SimplePassedTest -->
        <test-method signature="testT05_SimpleExpectedFailedTest()[pri:5, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:04 UTC" name="testT05_SimpleExpectedFailedTest" finished-at="2021-11-25T07:07:05 UTC" duration-ms="1017" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing for reasons...]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing for reasons...
at org.testng.Assert.fail(Assert.java:99)
at eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest.testT05_SimpleExpectedFailedTest(SimpleTest.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at eu.tsystems.mms.tic.testframework.report.hooks.TestMethodHook.runHook(TestMethodHook.java:60)
at eu.tsystems.mms.tic.testframework.report.TesterraListener.run(TesterraListener.java:433)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT05_SimpleExpectedFailedTest -->
        <test-method retried="true" signature="testT06_RetriedTestSecondRunPassed()[pri:6, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:04 UTC" name="testT06_RetriedTestSecondRunPassed" finished-at="2021-11-25T07:07:04 UTC" duration-ms="9" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testT05_RetriedTestSecondRunPassed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testT05_RetriedTestSecondRunPassed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest.testT06_RetriedTestSecondRunPassed(SimpleTest.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at eu.tsystems.mms.tic.testframework.report.hooks.TestMethodHook.runHook(TestMethodHook.java:60)
at eu.tsystems.mms.tic.testframework.report.TesterraListener.run(TesterraListener.java:433)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT06_RetriedTestSecondRunPassed -->
        <test-method signature="testT04_SkippedTest()[pri:4, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:04 UTC" name="testT04_SkippedTest" finished-at="2021-11-25T07:07:04 UTC" depends-on-methods="eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest.testT03_SimpleFailedTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SimpleTest.testT04_SkippedTest()[pri:4, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SimpleTest.testT04_SkippedTest()[pri:4, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT04_SkippedTest -->
        <test-method signature="testT06_RetriedTestSecondRunPassed()[pri:6, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:04 UTC" name="testT06_RetriedTestSecondRunPassed" finished-at="2021-11-25T07:07:04 UTC" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testT06_RetriedTestSecondRunPassed -->
        <test-method signature="test07_VerifyTeamCityMessages()[pri:999, instance:eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest@75961f16]" started-at="2021-11-25T07:07:04 UTC" name="test07_VerifyTeamCityMessages" finished-at="2021-11-25T07:07:04 UTC" duration-ms="9" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest.test07_VerifyTeamCityMessages(SimpleTest.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at eu.tsystems.mms.tic.testframework.report.hooks.TestMethodHook.runHook(TestMethodHook.java:60)
at eu.tsystems.mms.tic.testframework.report.TesterraListener.run(TesterraListener.java:433)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test07_VerifyTeamCityMessages -->
      </class> <!-- eu.tsystems.mms.tic.testerra.plugins.teamcity.test.SimpleTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
